<a href="https://colab.research.google.com/github/rajputankur56/numpy_tutor/blob/master/numpy_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
# create a array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
# array upcast to float
arr = np.array([1,2,3,4.0])
arr

array([1., 2., 3., 4.])

In [6]:
## upcast to string
arr = np.array([1,2,3.0,'hello'])
arr

array(['1', '2', '3.0', 'hello'], dtype='<U32')

In [7]:
# specifying data type
arr = np.array([1,2,3,4.0],dtype = np.int64)
arr

array([1, 2, 3, 4])

In [11]:
##multidimesional array

mulArr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
# mul = np.array([[1,2,3],[4,5,6]])
mulArr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
## array of zeros

arr = np.zeros(5)
arr

arr =np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
## array of ones

arr = np.ones(5)
arr
one = np.ones(5,dtype = np.int32)
one
one2  = np.ones((2,3),dtype = np.int64)
one2

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
## random number in numpy array

arr = np.random.rand(5)
arr

arr = np.random.rand(2,3)
arr

array([[0.51651625, 0.0791668 , 0.02918575],
       [0.30756353, 0.39446801, 0.20170887]])

In [25]:
## array of choice 

arr = np.full(5,7)
arr

arr = np.full((2,2),9)
arr

arr = np.full((2,2,2),9)
arr

array([[[9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9]]])

In [29]:
## create matrix indentity matrix

arr = np.eye(5)
arr

# to move value 1 to upper diagonal specify k
arr = np.eye(5,k=1)
arr

arr = np.eye(5,k=-2)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [34]:
## create a a range array
arr = np.arange(5)
arr
arr = np.arange(1,20,3)
arr
arr = np.arange(0,2,3)
arr
# #linspace
arr = np.linspace(0,10,7)
arr

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [37]:
## check dimensions or axes of array
arr = np.eye(5)
arr.ndim

## check shape of array
arr.shape

(5, 5)

In [39]:
# size of an array
arr.size

25

In [46]:
# reshape a array
arr = np.array([1,2,3,4,5,6])

arr = np.reshape(arr,(3,2))
arr

## specifying -1 when we are not sure about calue of rows or columns with given elements in array, at least one dimension should be given
arr = np.reshape(arr,(-1,3))
arr
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr = np.reshape(arr,(2,-1))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [57]:
## flatten a array
arr = np.eye(5)
arr

a = arr.flatten()
a[0] =5
a
arr

arr = np.eye(5)
a = arr.ravel()
a[0] = 5
a
arr

array([[5., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
## transpose a matrix

arr = np.ones((2,3))
arr

arr = arr.transpose()
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [69]:
## expand dimensions

arr = np.array([[1,2,3,4,5,6],[7,8,9,0,11,12]])
arr
arr.shape
# arr = np.expand_dims(arr,axis=0)
# arr
# arr.shape
arr = np.expand_dims(arr,axis=1)
arr
arr.shape

(2, 1, 6)

In [74]:
## squeeze dimensions

arr = np.array([[[1,2,3],[4,5,6]]])
arr
arr.shape
arr = np.squeeze(arr,axis =0)
arr
arr.shape

(2, 3)

In [83]:
## indexing and slicing
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[0:6]
arr[0:6:2]
arr[:]
arr[1::]
arr[1::2]
arr[:5:]
arr[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
#slicing
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr[1:,2:3]

array([[7]])

In [86]:
#slicing on 3d
a = np.array([[[1,2],[3,4],[5,6]],# first axis array
[[7,8],[9,10],[11,12]],# second axis array
[[13,14],[15,16],[17,18]]])# third axis array
# 3-D array
a
## try to play with teaking values
a[0:1,0:,0:]

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [87]:
# negative slicing
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
# print(a[:,-2])
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])
print('Reversed array :','\n',np.flip(a,axis = 0))
print('Reversed array :','\n',np.flip(a,axis = 1))

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]
Reversed array : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
Reversed array : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
