<a href="https://colab.research.google.com/github/rajputankur56/numpy_tutor/blob/master/numpy_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
# create a array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
# array upcast to float
arr = np.array([1,2,3,4.0])
arr

array([1., 2., 3., 4.])

In [6]:
## upcast to string
arr = np.array([1,2,3.0,'hello'])
arr

array(['1', '2', '3.0', 'hello'], dtype='<U32')

In [7]:
# specifying data type
arr = np.array([1,2,3,4.0],dtype = np.int64)
arr

array([1, 2, 3, 4])

In [11]:
##multidimesional array

mulArr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
# mul = np.array([[1,2,3],[4,5,6]])
mulArr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
## array of zeros

arr = np.zeros(5)
arr

arr =np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
## array of ones

arr = np.ones(5)
arr
one = np.ones(5,dtype = np.int32)
one
one2  = np.ones((2,3),dtype = np.int64)
one2

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
## random number in numpy array

arr = np.random.rand(5)
arr

arr = np.random.rand(2,3)
arr

array([[0.51651625, 0.0791668 , 0.02918575],
       [0.30756353, 0.39446801, 0.20170887]])

In [25]:
## array of choice 

arr = np.full(5,7)
arr

arr = np.full((2,2),9)
arr

arr = np.full((2,2,2),9)
arr

array([[[9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9]]])

In [29]:
## create matrix indentity matrix

arr = np.eye(5)
arr

# to move value 1 to upper diagonal specify k
arr = np.eye(5,k=1)
arr

arr = np.eye(5,k=-2)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [34]:
## create a a range array
arr = np.arange(5)
arr
arr = np.arange(1,20,3)
arr
arr = np.arange(0,2,3)
arr
# #linspace
arr = np.linspace(0,10,7)
arr

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [37]:
## check dimensions or axes of array
arr = np.eye(5)
arr.ndim

## check shape of array
arr.shape

(5, 5)

In [39]:
# size of an array
arr.size

25

In [46]:
# reshape a array
arr = np.array([1,2,3,4,5,6])

arr = np.reshape(arr,(3,2))
arr

## specifying -1 when we are not sure about calue of rows or columns with given elements in array, at least one dimension should be given
arr = np.reshape(arr,(-1,3))
arr
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr = np.reshape(arr,(2,-1))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [57]:
## flatten a array
arr = np.eye(5)
arr

a = arr.flatten()
a[0] =5
a
arr

arr = np.eye(5)
a = arr.ravel()
a[0] = 5
a
arr

array([[5., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
## transpose a matrix

arr = np.ones((2,3))
arr

arr = arr.transpose()
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [69]:
## expand dimensions

arr = np.array([[1,2,3,4,5,6],[7,8,9,0,11,12]])
arr
arr.shape
# arr = np.expand_dims(arr,axis=0)
# arr
# arr.shape
arr = np.expand_dims(arr,axis=1)
arr
arr.shape

(2, 1, 6)

In [74]:
## squeeze dimensions

arr = np.array([[[1,2,3],[4,5,6]]])
arr
arr.shape
arr = np.squeeze(arr,axis =0)
arr
arr.shape

(2, 3)

In [83]:
## indexing and slicing
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[0:6]
arr[0:6:2]
arr[:]
arr[1::]
arr[1::2]
arr[:5:]
arr[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
#slicing
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr[1:,2:3]

array([[7]])

In [86]:
#slicing on 3d
a = np.array([[[1,2],[3,4],[5,6]],# first axis array
[[7,8],[9,10],[11,12]],# second axis array
[[13,14],[15,16],[17,18]]])# third axis array
# 3-D array
a
## try to play with teaking values
a[0:1,0:,0:]

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [87]:
# negative slicing
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
# print(a[:,-2])
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])
print('Reversed array :','\n',np.flip(a,axis = 0))
print('Reversed array :','\n',np.flip(a,axis = 1))

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]
Reversed array : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
Reversed array : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]


**Stacking and concatenating array**

In [92]:
a = np.arange(0,5)
b = np.arange(5,10)
a
b
c = np.vstack((a,b))
c
d = np.hstack((a,b))
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = np.dstack((a,b))
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Dstack :','\n',c)
print(c.shape)

Array 1 : 
 [[1, 2], [3, 4]]
Array 2 : 
 [[5, 6], [7, 8]]
Dstack : 
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [95]:
# concatenate
a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Concatenate along rows :','\n',np.concatenate((a,b),axis=0))
print('Concatenate along columns :','\n',np.concatenate((a,b),axis=1))

Array 1 : 
 [[0 1 2 3 4]]
Array 2 : 
 [[5 6 7 8 9]]
Concatenate along rows : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Concatenate along columns : 
 [[0 1 2 3 4 5 6 7 8 9]]


In [97]:
## append values to an array
a = np.eye(3)
a=np.append(a,[[2,3,2]],axis = 0)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [2., 3., 2.]])

In [98]:
## broadcasting
a = np.arange(10,20,2)
b = np.array([[2],[2]])
print('Adding two different size arrays :','\n',a+b)
print('Multiplying an ndarray and a number :',a*2)

Adding two different size arrays : 
 [[12 14 16 18 20]
 [12 14 16 18 20]]
Multiplying an ndarray and a number : [20 24 28 32 36]


In [99]:
## ufunc or universal functions
a = [1,2,3,4,5]
b = [6,7,8,9,10]
%timeit a+b
a = np.arange(1,6)
b = np.arange(6,11)
%timeit a+b

10000000 loops, best of 3: 82.9 ns per loop
The slowest run took 31.94 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 570 ns per loop


In [100]:
## maths
a = np.array([1,2,3,4,5])
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [-4 -3 -2 -1  0]
Multiply : [ 5 10 15 20 25]
Divide : [0.2 0.4 0.6 0.8 1. ]
Power : [ 1  4  9 16 25]
Remainder : [1 2 3 4 0]


In [102]:
## central tendency and dispersion
a = np.arange(5,15,2)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [103]:
## min max and thier index
a = np.array([[1,6],
[4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


In [105]:
## to check index of min and max values
a = np.array([[1,6,5],
[4,3,7]])
# minimum along a column
print('Min :',np.argmin(a,axis=0))
# maximum along a row
print('Max :',np.argmax(a,axis=1))

Min : [0 1 0]
Max : [1 2]


In [107]:
## sorting 
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a, kind='quicksort')
a = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the column
print("Array :\n",a)
print('Sort along column :','\n',np.sort(a, kind='mergresort',axis=1))
# sort along the row
print('Sort along row :','\n',np.sort(a, kind='mergresort',axis=0))

Array :
 [[5 6 7 4]
 [9 2 3 7]]
Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]


In [108]:
#import numpy as np
import matplotlib.pyplot as plt
from scipy import misc

dir(misc)
# read image
im = misc.__loader__#('./original.jpg')
im
# image
# im